name: DockerPush

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.HYPERJUMP_DOCKER_USERNAME}}
          password: ${{secrets.HYPERJUMP_DOCKER_PASSWORD}}
      - name: Build and push API
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hyperjump/symon-api:latest
          file: "Dockerfile.server"
      - name: Build and push Frontend
        id: docker_build_fe
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: hyperjump/symon-frontend:latest
          file: "Dockerfile.client"
